/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as prlxAirdropSol from "./PRLXAirdrop.sol";
export type { prlxAirdropSol };
export type { Lock } from "./Lock";
